Test osxarm env

diff --git a/.github/workflows/TestMac.yml b/.github/workflows/TestMac.yml
--- a/.github/workflows/TestMac.yml
+++ b/.github/workflows/TestMac.yml
@@ -8,44 +8,39 @@ jobs:
   build-ledfx-osx:
     name: Build LedFx (OS X) (Apple Silicon)
     runs-on: osx-arm64
+    defaults:
+      run:
+        shell: bash -x {0}
     strategy:
       matrix:
         python: [3.12.x]
     steps:
-      - name: Check out code from GitHub
-        uses: actions/checkout@v4
-        with:
-          repository: LedFx/LedFx
-        
       - name: Install build dependencies
         run: |
-          brew install portaudio
-          brew install mbedtls@2
-          brew install libsamplerate
+          arch -arm64 brew install portaudio
+          arch -arm64 brew install mbedtls@2
+          arch -arm64 brew install libsamplerate
+          arch -arm64 brww install poetry
       - name: Setup mbedtls path
         run: |
           echo "/opt/homebrew/opt/mbedtls@2/bin" >> $GITHUB_PATH
-      - name: Setup Python ${{ matrix.python }}
-        id: python
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python }}
-      - name: Install poetry via Homebrew
+      - name: Check Python version
         run: |
-          brew install poetry
-      - name: Build LedFx wheel
-        run: |
-          poetry build
-      - name: Install LedFx from wheel
-        run: |
-          export LDFLAGS="-L/opt/homebrew/opt/mbedtls@2/lib"
-          export CPPFLAGS="-I/opt/homebrew/opt/mbedtls@2/include"
-          poetry install
-      - name: Smoketest LedFx
-        run: |
-          source $(poetry env info -p)/bin/activate
-          ledfx --ci-smoke-test
-          if [ $? -ne 0 ]; then
-            echo "LedFx launch failed: $?"
-            exit 1
-          fi
+        arch -arm64 python -V
+        arch -arm64 python3 -V
+      # - name: Build LedFx wheel
+      #   run: |
+      #     poetry build
+      # - name: Install LedFx from wheel
+      #   run: |
+      #     export LDFLAGS="-L/opt/homebrew/opt/mbedtls@2/lib"
+      #     export CPPFLAGS="-I/opt/homebrew/opt/mbedtls@2/include"
+      #     poetry install
+      # - name: Smoketest LedFx
+      #   run: |
+      #     source $(poetry env info -p)/bin/activate
+      #     ledfx --ci-smoke-test
+      #     if [ $? -ne 0 ]; then
+      #       echo "LedFx launch failed: $?"
+      #       exit 1
+      #     fi
